#!/bin/bash

# Apps
env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify --disable-gpu &
# discord &
#vesktop &
webcord &
thunderbird &
# obsidian &

# Terminal Apps
kitty --class btop btop &
kitty --class nvtop nvtop &
