#!/bin/bash

# Apps
#LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify --enable-features=UseOzonePlatform --ozone-platform-wayland &
env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify --disable-gpu &
discord &
thunderbird &
obsidian &

# Terminal Apps
kitty --class btop btop &
kitty --class nvtop nvtop &
