#!/bin/bash

# Variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Plugins
pypr &

# Notification Daemon
swaync &

# Wallpaper Backend
#exec "$scripts/swwwallpaper.sh" &  # wallpaper daemon
exec "$scripts/swwwallrandom.sh" & # wallpaper random

# Bar
waybar &

# OSD Window
swayosd-server &

# Automounter for removable media
udiskie &

# Notify about devices connecting and disconnecting
devify &

# Idle daemon to screen lock
swayidle &

# Clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

# Polkit authentication
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec "$scripts/Polkit.sh" & # Polkit (Polkit Gnome / KDE)

# Screen sharing and portals
exec "$scripts/portal" &
# xwaylandvideobridge &

# Audio
easyeffects --gapplication-service &
