#!/bin/bash
#  _              _     _           _ _
# | | _____ _   _| |__ (_)_ __   __| (_)_ __   __ _ ___
# | |/ / _ \ | | | '_ \| | '_ \ / _` | | '_ \ / _` / __|
# |   <  __/ |_| | |_) | | | | | (_| | | | | | (_| \__ \
# |_|\_\___|\__, |_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#           |___/                             |___/
# by Stephan Raabe (2023)
# -----------------------------------------------------

# -----------------------------------------------------
# Get keybindings location based on variation
# -----------------------------------------------------
config_file=~/.config/hypr/configs/binds.conf
#config_file=${config_file/source = ~/}
#config_file=${config_file/source=~/}

# -----------------------------------------------------
# Path to keybindings config file
# -----------------------------------------------------
#config_file="/home/$USER$config_file"
echo "Reading from: $config_file"

# -----------------------------------------------------
# Parse keybindings
# -----------------------------------------------------
keybinds=$(grep -oP '(?<=bind = ).*' $config_file)
keybinds=$(echo "$keybinds" | sed 's/code://g' | sed 's/, 23/, TAB/g' | sed 's/, 107/, PRINT_SCREEN/g' | sed 's/, 61/, !/g' | sed 's/, 51/, BACKSLASH/g')
keybinds=$(echo "$keybinds" | sed 's/, 10/, 1/g' | sed 's/, 11/, 2/g' | sed 's/, 12/, 3/g' | sed 's/, 13/, 4/g' | sed 's/, 14/, 5/g' | sed 's/, 15/, 6/g' | sed 's/, 16/, 7/g' | sed 's/, 17/, 8/g' | sed 's/, 18/, 9/g' | sed 's/, 19/, 10/g')
keybinds=$(echo "$keybinds" | sed 's/~\/.config\/rofi\/launchers\/type-7\///g' | sed 's/~\/.config\/rofi\/applets\/bin\///g' | sed 's/~\/.config\/hypr\/scripts\/rofi\///g' | sed 's/~\/.config\/hypr\/scripts\///g')
keybinds=$(echo "$keybinds" | sed 's/$mainMod/SUPER/g' | sed 's/$app_launcher //g' | sed 's/,\([^,]*\)$/ = \1/' | sed 's/, exec//g' | sed 's/^,//g')

# -----------------------------------------------------
# Show keybindings in rofi
# -----------------------------------------------------
rofi -dmenu -i -replace -p "Keybinds" -theme ~/.config/rofi/keybindings.rasi <<<"$keybinds"
