#!/bin/bash
# dotfiles/.config/hypr/scripts/portal
# This script is used to start the xdg-desktop-portal-hyprland and xdg-desktop-portal

sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal
sleep 1
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
